### ISSUE TITLE
[iOS] 메인뷰 - 앱을 재시작해도 이전에 선택한 셀이 메인 셀에 그대로 표시되어 있어야 한다.

### ISSUE THREAD

**Issue by eojine** [boostcamp-2020/Project03-A-TOTP#39]
## :bulb: 이슈 내용
> 선택한 토큰은 메인 셀에 상세한 정보 표시 
- 앱을 재시작해도 이전에 선택한 셀이 메인 셀에 그대로 표시되어 있어야 한다.

## :white_check_mark: 작업 내용
- [x] 학습: PropertyWrapper를 통한 UserDefaults 저장 방법
- [x] 구현: 선택될 셀 UserDefaults에 저장
- [x] 테스트

**Comment by jjm159** [comment]
따로 MainCell이 무엇인지에 대한 정보를 따로 관리하여 UserDefault를 사용하여 저장하는 것을 하지 않고, Token 객체 안에 isMain 속성을 두어 사용했다. 다른 디바이스에서도 mainCell이 공유되려면, Token 안에 이 속성을 추가하는게 더 낫다고 판단했다.
